#!/bin/bash
cd ../../app/public
while [ 1 ]
do
  echo -e "\n\nPirateScrolls Papers"
  echo "********************"
  echo "0) Quit program"
  echo "1) Compress papers"
  echo "2) Set up papers"
  read -p ">> " c
  [ "$c" == 0 ] && echo "Gracefully quitting..." && exit
  [ "$c" == 1 ] && 7z a -mx=9 papers.7z files && rm -rf files
  [ "$c" == 2 ] && 7z e papers.7z && rm -rf papers.7z && mv paper* files
done


